CREATE TABLE [dbo].[TransportSaleAnnounces]
(
	[Id]				 INT			NOT NULL,
	[AdNumber]			 BIGINT			NOT NULL,
	[Year]				 INT			NOT NULL,
	[Price]				 FLOAT			NOT NULL,
	[SourceLink]		 NVARCHAR(512)	NOT NULL,
	[ImageLink]			 NVARCHAR(512)	NOT NULL,
	[Description]		 NVARCHAR(512)	NOT NULL,
	[EngineVolumetric]	 INT			NOT NULL,
	[UpdateOfferTime]	 DateTime		NOT NULL,
	[BodyTypeId]		 INT			NOT NULL,
	[TranssmisionTypeId] INT			NOT NULL,
	[CityId]			 INT			NOT NULL,
	[FuelTypeId]		 INT			NOT NULL,
	[ModelId]			 INT			NOT NULL,
	[SourceProviderId]   INT			NOT NULL,
	[CreatedAt]			DATETIME		NULL, 
	[UpdatedAt]			DATETIME		NULL, 
	[DeletedAt]			DATETIME		NULL,
	CONSTRAINT	[PK_TransportSaleAnnounces] PRIMARY KEY CLUSTERED ([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_BodyTypeId] FOREIGN KEY ([BodyTypeId]) REFERENCES [dbo].[BodyTypes]	([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_TranssmisionTypeId] FOREIGN KEY ([TranssmisionTypeId]) REFERENCES [dbo].[TransmissionTypes]	([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_CityId] FOREIGN KEY ([CityId]) REFERENCES [dbo].[Cities]	([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_FuelTypeId] FOREIGN KEY ([FuelTypeId]) REFERENCES [dbo].[FuelTypes] ([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_ModelId] FOREIGN KEY ([ModelId]) REFERENCES [dbo].[TransportModels] ([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_SourceProviderId] FOREIGN KEY ([SourceProviderId]) REFERENCES [dbo].[TransportSourceProviders] ([Id]),
)
