CREATE TABLE [dbo].[TransportSaleAnnounces]
(
	[Id]				 INT			NOT NULL IDENTITY(1, 1),
	[AdNumber]			 BIGINT			NOT NULL,
	[Year]				 INT			NOT NULL,
	[PriceInDollars]	 FLOAT			NOT NULL,
	[SourceLink]		 NVARCHAR(512)	NOT NULL,
	[PreviewImageLink]	 NVARCHAR(512)	NOT NULL,
	[Description]		 NVARCHAR(MAX)	NOT NULL,
	[EngineVolumetric]	 INT			NOT NULL,
	[UpdateOfferTime]	 DateTime		NOT NULL,
	[BodyTypeId]		 INT		    NULL,
	[TransmissionTypeId] INT			NOT NULL,
	[CityId]			 INT			NOT NULL,
	[FuelTypeId]		 INT			NOT NULL,
	[BrandId]			 INT		    NULL,
	[ModelId]			 INT		    NULL,
	[VehicleTypeId]		 INT		    NOT NULL,
	[DriveUnitId]		 INT		    NOT NULL,
	[Mileage]			 INT			NOT NULL,
	[IsDeleted]			BIT				DEFAULT 0 NOT NULL,
	[CreatedAt]			DATETIME		NULL, 
	[UpdatedAt]			DATETIME		NULL, 
	[DeletedAt]			DATETIME		NULL,
	CONSTRAINT	[PK_TransportSaleAnnounces] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT  [FK_TransportSaleAnnounces_BodyTypeId] FOREIGN KEY ([BodyTypeId]) REFERENCES [dbo].[BodyTypes]	([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_TranssmisionTypeId] FOREIGN KEY ([TransmissionTypeId]) REFERENCES [dbo].[TransmissionTypes]	([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_CityId] FOREIGN KEY ([CityId]) REFERENCES [dbo].[Cities]	([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_FuelTypeId] FOREIGN KEY ([FuelTypeId]) REFERENCES [dbo].[FuelTypes] ([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_ModelId] FOREIGN KEY ([ModelId]) REFERENCES [dbo].[TransportModels] ([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_BrandId] FOREIGN KEY ([BrandId]) REFERENCES [dbo].[TransportBrands] ([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_VehicleTypeId] FOREIGN KEY ([VehicleTypeId]) REFERENCES [dbo].[VehicleTypes] ([Id]),
	CONSTRAINT  [FK_TransportSaleAnnounces_DriveUnitId] FOREIGN KEY ([DriveUnitId]) REFERENCES [dbo].[DriveUnits] ([Id])
)
