MERGE INTO [dbo].Countries AS Target
USING
(
	VALUES
	 (1, N'Andorra', N'AD', N'ca'),
	 (2, N'United Arab Emirates', N'AE', N'ar'),
	 (3, N'Afghanistan', N'AF', N'fa'),
	 (4, N'Antigua and Barbuda', N'AG', N'en'),
	 (5, N'Anguilla', N'AI', N'en'),
	 (6, N'Albania', N'AL', N'sq'),
	 (7, N'Armenia', N'AM', N'hy'),
	 (8, N'Netherlands Antilles', N'AN', N'nl'),
	 (9, N'Angola', N'AO', N'pt'),
	 (10, N'Argentina', N'AR', N'es'),
	 (11, N'Austria', N'AT', N'de'),
	 (12, N'Australia', N'AU', N'en'),
	 (13, N'Aruba', N'AW', N'nl'),
	 (14, N'Azerbaijan', N'AZ', N'az'),
	 (15, N'Bosnia and Herzegovina', N'BA', N'bs'),
	 (16, N'Barbados', N'BB', N'en'),
	 (17, N'Bangladesh', N'BD', N'bn'),
	 (18, N'Belgium', N'BE', N'nl'),
	 (19, N'Burkina Faso', N'BF', N'fr'),
	 (20, N'Bulgaria', N'BG', N'bg'),
	 (21, N'Bahrain', N'BH', N'ar'),
	 (22, N'Burundi', N'BI', N'fr'),
	 (23, N'Benin', N'BJ', N'fr'),
	 (24, N'Bermuda', N'BM', N'en'),
	 (25, N'Brunei Darussalam', N'BN', N'ms'),
	 (26, N'Bolivia', N'BO', N'es'),
	 (27, N'Brazil', N'BR', N'pt'),
	 (28, N'Bahamas', N'BS', N'en'),
	 (29, N'Bhutan', N'BT', N'dz'),
	 (30, N'Botswana', N'BW', N'en'),
	 (31, N'Belarus', N'BY', N'be'),
	 (32, N'Belize', N'BZ', N'en'),
	 (33, N'Canada', N'CA', N'en'),
	 (34, N'Cocos (Keeling), Islands', N'CC', N'en'),
	 (35, N'Democratic Republic of the Congo', N'CD', N'fr'),
	 (36, N'Central African Republic', N'CF', N'fr'),
	 (37, N'Congo', N'CG', N'fr'),
	 (38, N'Switzerland', N'CH', N'de'),
	 (39, N'Cote D''Ivoire (Ivory Coast),', N'CI', N'fr'),
	 (40, N'Cook Islands', N'CK', N'en'),
	 (41, N'Chile', N'CL', N'es'),
	 (42, N'Cameroon', N'CM', N'fr'),
	 (43, N'China', N'CN', N'zh'),
	 (44, N'Colombia', N'CO', N'es'),
	 (45, N'Costa Rica', N'CR', N'es'),
	 (46, N'Cuba', N'CU', N'es'),
	 (47, N'Cape Verde', N'CV', N'pt'),
	 (48, N'Christmas Island', N'CX', N'en'),
	 (49, N'Cyprus', N'CY', N'el'),
	 (50, N'Czech Republic', N'CZ', N'cs'),
	 (51, N'Germany', N'DE', N'de'),
	 (52, N'Djibouti', N'DJ', N'fr'),
	 (53, N'Denmark', N'DK', N'da'),
	 (54, N'Dominica', N'DM', N'en'),
	 (55, N'Dominican Republic', N'DO', N'es'),
	 (56, N'Algeria', N'DZ', N'ar'),
	 (57, N'Ecuador', N'EC', N'es'),
	 (58, N'Estonia', N'EE', N'et'),
	 (59, N'Egypt', N'EG', N'ar'),
	 (60, N'Western Sahara', N'EH', N'ar'),
	 (61, N'Eritrea', N'ER', N'ti'),
	 (62, N'Spain', N'ES', N'es'),
	 (63, N'Ethiopia', N'ET', N'am'),
	 (64, N'Finland', N'FI', N'fi'),
	 (65, N'Fiji', N'FJ', N'en'),
	 (66, N'Falkland Islands (Malvinas),', N'FK', N'en'),
	 (67, N'Federated States of Micronesia', N'FM', N'en'),
	 (68, N'Faroe Islands', N'FO', N'fo'),
	 (69, N'France', N'FR', N'fr'),
	 (70, N'Gabon', N'GA', N'fr'),
	 (71, N'Great Britain (UK),', N'GB', N'en'),
	 (72, N'Grenada', N'GD', N'en'),
	 (73, N'Georgia', N'GE', N'ka'),
	 (74, N'French Guiana', N'GF', N'fr'),
	 (75, N'Guernsey', N'GG', N'en'),
	 (76, N'Ghana', N'GH', N'en'),
	 (77, N'Gibraltar', N'GI', N'en'),
	 (78, N'Greenland', N'GL', N'kl'),
	 (79, N'Gambia', N'GM', N'en'),
	 (80, N'Guinea', N'GN', N'fr'),
	 (81, N'Guadeloupe', N'GP', N'fr'),
	 (82, N'Equatorial Guinea', N'GQ', N'es'),
	 (83, N'Greece', N'GR', N'el'),
	 (84, N'S. Georgia and S. Sandwich Islands', N'GS', N'en'),
	 (85, N'Guatemala', N'GT', N'es'),
	 (86, N'Guinea-Bissau', N'GW', N'pt'),
	 (87, N'Guyana', N'GY', N'en'),
	 (88, N'Hong Kong', N'HK', N'zh'),
	 (89, N'Honduras', N'HN', N'es'),
	 (90, N'Croatia (Hrvatska),', N'HR', N'hr'),
	 (91, N'Haiti', N'HT', N'fr'),
	 (92, N'Hungary', N'HU', N'hu'),
	 (93, N'Indonesia', N'ID', N'id'),
	 (94, N'Ireland', N'IE', N'en'),
	 (95, N'Israel', N'IL', N'he'),
	 (96, N'India', N'IN', N'hi'),
	 (97, N'Iraq', N'IQ', N'ar'),
	 (98, N'Iran', N'IR', N'fa'),
	 (99, N'Iceland', N'IS', N'is'),
	 (100, N'Italy', N'IT', N'it'),
	 (101, N'Jamaica', N'JM', N'en'),
	 (102, N'Jordan', N'JO', N'ar'),
	 (103, N'Japan', N'JP', N'ja'),
	 (104, N'Kenya', N'KE', N'sw'),
	 (105, N'Kyrgyzstan', N'KG', N'ky'),
	 (106, N'Cambodia', N'KH', N'km'),
	 (107, N'Kiribati', N'KI', N'en'),
	 (108, N'Comoros', N'KM', N'ar'),
	 (109, N'Saint Kitts and Nevis', N'KN', N'en'),
	 (110, N'Korea (North),', N'KP', N'ko'),
	 (111, N'Korea (South),', N'KR', N'ko'),
	 (112, N'Kuwait', N'KW', N'ar'),
	 (113, N'Cayman Islands', N'KY', N'en'),
	 (114, N'Kazakhstan', N'KZ', N'kk'),
	 (115, N'Laos', N'LA', N'lo'),
	 (116, N'Lebanon', N'LB', N'ar'),
	 (117, N'Saint Lucia', N'LC', N'en'),
	 (118, N'Liechtenstein', N'LI', N'de'),
	 (119, N'Sri Lanka', N'LK', N'si'),
	 (120, N'Liberia', N'LR', N'en'),
	 (121, N'Lesotho', N'LS', N'en'),
	 (122, N'Lithuania', N'LT', N'lt'),
	 (123, N'Luxembourg', N'LU', N'lb'),
	 (124, N'Latvia', N'LV', N'lv'),
	 (125, N'Libya', N'LY', N'ar'),
	 (126, N'Morocco', N'MA', N'fr'),
	 (127, N'Monaco', N'MC', N'fr'),
	 (128, N'Moldova', N'MD', N'ro'),
	 (129, N'Madagascar', N'MG', N'mg'),
	 (130, N'Marshall Islands', N'MH', N'en'),
	 (131, N'Macedonia', N'MK', N'mk'),
	 (132, N'Mali', N'ML', N'fr'),
	 (133, N'Myanmar', N'MM', N'my'),
	 (134, N'Mongolia', N'MN', N'mn'),
	 (135, N'Macao', N'MO', N'zh'),
	 (136, N'Northern Mariana Islands', N'MP', N'en'),
	 (137, N'Martinique', N'MQ', N'fr'),
	 (138, N'Mauritania', N'MR', N'ar'),
	 (139, N'Montserrat', N'MS', N'en'),
	 (140, N'Malta', N'MT', N'mt'),
	 (141, N'Mauritius', N'MU', N'mfe'),
	 (142, N'Maldives', N'MV', N'dv'),
	 (143, N'Malawi', N'MW', N'en'),
	 (144, N'Mexico', N'MX', N'es'),
	 (145, N'Malaysia', N'MY', N'ms'),
	 (146, N'Mozambique', N'MZ', N'pt'),
	 (147, N'Namibia', N'NA', N'en'),
	 (148, N'New Caledonia', N'NC', N'fr'),
	 (149, N'Niger', N'NE', N'fr'),
	 (150, N'Norfolk Island', N'NF', N'en'),
	 (151, N'Nigeria', N'NG', N'en'),
	 (152, N'Nicaragua', N'NI', N'es'),
	 (153, N'Netherlands', N'NL', N'nl'),
	 (154, N'Norway', N'NO', N'nb'),
	 (155, N'Nepal', N'NP', N'ne'),
	 (156, N'Nauru', N'NR', N'na'),
	 (157, N'Niue', N'NU', N'niu'),
	 (158, N'New Zealand (Aotearoa),', N'NZ', N'mi'),
	 (159, N'Oman', N'OM', N'ar'),
	 (160, N'Panama', N'PA', N'es'),
	 (161, N'Peru', N'PE', N'es'),
	 (162, N'French Polynesia', N'PF', N'fr'),
	 (163, N'Papua New Guinea', N'PG', N'en'),
	 (164, N'Philippines', N'PH', N'en'),
	 (165, N'Pakistan', N'PK', N'en'),
	 (166, N'Poland', N'PL', N'pl'),
	 (167, N'Saint Pierre and Miquelon', N'PM', N'fr'),
	 (168, N'Pitcairn', N'PN', N'en'),
	 (169, N'Palestinian Territory', N'PS', N'ar'),
	 (170, N'Portugal', N'PT', N'pt'),
	 (171, N'Palau', N'PW', N'en'),
	 (172, N'Paraguay', N'PY', N'es'),
	 (173, N'Qatar', N'QA', N'ar'),
	 (174, N'Reunion', N'RE', N'fr'),
	 (175, N'Romania', N'RO', N'ro'),
	 (176, N'Russian Federation', N'RU', N'ru'),
	 (177, N'Rwanda', N'RW', N'rw'),
	 (178, N'Saudi Arabia', N'SA', N'ar'),
	 (179, N'Solomon Islands', N'SB', N'en'),
	 (180, N'Seychelles', N'SC', N'fr'),
	 (181, N'Sudan', N'SD', N'ar'),
	 (182, N'Sweden', N'SE', N'sv'),
	 (183, N'Singapore', N'SG', N'zh'),
	 (184, N'Saint Helena', N'SH', N'en'),
	 (185, N'Slovenia', N'SI', N'sl'),
	 (186, N'Svalbard and Jan Mayen', N'SJ', N'no'),
	 (187, N'Slovakia', N'SK', N'sk'),
	 (188, N'Sierra Leone', N'SL', N'en'),
	 (189, N'San Marino', N'SM', N'it'),
	 (190, N'Senegal', N'SN', N'fr'),
	 (191, N'Somalia', N'SO', N'so'),
	 (192, N'Suriname', N'SR', N'nl'),
	 (193, N'Sao Tome and Principe', N'ST', N'pt'),
	 (194, N'El Salvador', N'SV', N'es'),
	 (195, N'Syria', N'SY', N'ar'),
	 (196, N'Swaziland', N'SZ', N'en'),
	 (197, N'Turks and Caicos Islands', N'TC', N'en'),
	 (198, N'Chad', N'TD', N'fr'),
	 (199, N'French Southern Territories', N'TF', N'fr'),
	 (200, N'Togo', N'TG', N'fr'),
	 (201, N'Thailand', N'TH', N'th'),
	 (202, N'Tajikistan', N'TJ', N'tg'),
	 (203, N'Tokelau', N'TK', N'tkl'),
	 (204, N'Turkmenistan', N'TM', N'tk'),
	 (205, N'Tunisia', N'TN', N'ar'),
	 (206, N'Tonga', N'TO', N'en'),
	 (207, N'Turkey', N'TR', N'tr'),
	 (208, N'Trinidad and Tobago', N'TT', N'en'),
	 (209, N'Tuvalu', N'TV', N'en'),
	 (210, N'Taiwan', N'TW', N'zh'),
	 (211, N'Tanzania', N'TZ', N'sw'),
	 (212, N'Ukraine', N'UA', N'uk'),
	 (213, N'Uganda', N'UG', N'en'),
	 (214, N'Uruguay', N'UY', N'es'),
	 (215, N'Uzbekistan', N'UZ', N'uz'),
	 (216, N'Saint Vincent and the Grenadines', N'VC', N'en'),
	 (217, N'Venezuela', N'VE', N'es'),
	 (218, N'Virgin Islands (British),', N'VG', N'en'),
	 (219, N'Virgin Islands (U.S.),', N'VI', N'en'),
	 (220, N'Viet Nam', N'VN', N'vi'),
	 (221, N'Vanuatu', N'VU', N'bi'),
	 (222, N'Wallis and Futuna', N'WF', N'fr'),
	 (223, N'Samoa', N'WS', N'sm'),
	 (224, N'Yemen', N'YE', N'ar'),
	 (225, N'Mayotte', N'YT', N'fr'),
	 (226, N'South Africa', N'ZA', N'en'),
	 (227, N'Zambia', N'ZM', N'en'),
	 (228, N'Zaire (former),', N'ZR', N'fr'),
	 (229, N'Zimbabwe', N'ZW', N'en'),
	 (230, N'United States of America', N'US', N'en')
) AS Source ([Id], [Name], [Code], [Language])
ON (Target.[Id] = Source.[Id])
WHEN NOT MATCHED THEN
	INSERT ([Id], [Name], [Code], [Language])
	VALUES (Source.[Id], Source.[Name], Source.[Code], Source.[Language]);